"""Added is_alive.

Revision ID: 134bfb4c64dd
Revises: 757e99567169
Create Date: 2023-11-06 21:15:18.963272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134bfb4c64dd'
down_revision = '757e99567169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alive', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=120), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('is_alive')

    # ### end Alembic commands ###
