"""Added field place of born.

Revision ID: 42a520e871ec
Revises: 3402ce49ea15
Create Date: 2023-11-09 19:06:44.853506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a520e871ec'
down_revision = '3402ce49ea15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_of_born', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('place_of_born')

    # ### end Alembic commands ###
