"""Added document field.

Revision ID: 443354a0f685
Revises: 155b897b4b00
Create Date: 2023-11-12 20:46:17.737329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443354a0f685'
down_revision = '155b897b4b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=150), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_file_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file'))
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=150), nullable=True))

    op.drop_table('file')
    # ### end Alembic commands ###
