"""Added parents.

Revision ID: 57c7ae944f95
Revises: 0cf0ee471d9c
Create Date: 2023-11-07 20:54:03.128836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c7ae944f95'
down_revision = '0cf0ee471d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('father_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['father_id'], ['id'])
        batch_op.create_foreign_key(None, 'person', ['mother_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('father_id')
        batch_op.drop_column('mother_id')

    # ### end Alembic commands ###
