"""Added field place of born.

Revision ID: f51ec86b7d7d
Revises: 9c4e2a3a175d
Create Date: 2023-11-11 04:40:44.312785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51ec86b7d7d'
down_revision = '9c4e2a3a175d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_of_birth', sa.String(length=120), nullable=True))
        batch_op.drop_column('place_of_born')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_of_born', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('place_of_birth')

    # ### end Alembic commands ###
