"""Your message about the migration

Revision ID: f7843fa68d3a
Revises: 57c7ae944f95
Create Date: 2023-11-07 21:05:59.078205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7843fa68d3a'
down_revision = '57c7ae944f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('fk_person_father_id_person', type_='foreignkey')
        batch_op.drop_constraint('fk_person_mother_id_person', type_='foreignkey')
        batch_op.drop_column('mother_id')
        batch_op.drop_column('father_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mother_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_person_mother_id_person', 'person', ['mother_id'], ['id'])
        batch_op.create_foreign_key('fk_person_father_id_person', 'person', ['father_id'], ['id'])

    # ### end Alembic commands ###
